name: docker

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/hiroyaonoe/texlive:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
